VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "classe_listv_Usf_Lab_listview"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
''''Public WithEvents Groupelistv As MSForms.ListBox
''''Public Sub Groupelistv_Click()
'''''Private Sub Groupelistv_change()
''''    TextMem = Groupelistv.Name
''''    txtrow = Right(TextMem, Len(TextMem) - 7)
''''    If Groupelistv.Text = "" Then Exit Sub
''''    If txtrow = 3 Then
''''        For i = 1 To ListView1.ListItems.Count
''''            ListView1.ListItems(i).Checked = False
''''        Next i
''''
''''
''''            USF_Inst_fact("TextBox3").Value = USF_Inst_fact("ComboBox2").Value
'''''            Call USF_Inst_fact.affiche3
''''            trig = False
''''        End If
''''
''''End Sub
