VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "classe_textb_Usf_client_edit"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public WithEvents GroupeTextb2 As MSForms.TextBox
Attribute GroupeTextb2.VB_VarHelpID = -1
'Public Sub GroupeTextb_Mousedown(ByVal Button As Integer, ByVal Shift As Integer, ByVal X As Single, ByVal Y As Single)
Private Sub GroupeTextb2_change()
'    If (GroupeTextb.Name = "Textbox28") Then
'        Application.EnableEvents = False
'        For i = 1 To Len(GroupeTextb.Text)
'            sstr1 = Mid(GroupeTextb.Text, i, 1)
'            If Not sstr1 Like "#" Then Exit Sub
'        Next i
'        Application.EnableEvents = True
'    End If
End Sub
