VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "classe_combo_USF_NewTarif_List"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
Public WithEvents GroupeCombo As MSForms.ComboBox
Attribute GroupeCombo.VB_VarHelpID = -1
''Public Sub GroupeCombo_change()
''    Dim combomem, combomem2, sstr4, cmbrow, cmbcol As String
''    combomem = GroupeCombo.text
''    USF_Command_List.Frame1("Textbox11").text = combomem
''    Call tri_col_generic(Sheets("CLIENTS"), 14)
''Dim Sep$
''Sep = Application.International(xlDecimalSeparator)
''TextBox = Replace(TextBox1, ".", Sep)
''TextBox1 = Replace(TextBox1, ",", Sep)
''End Sub

